creation_rules:
  - path_regex: 'charts\/.*\/production\/(.*).yaml'
    # Replace with your KMS key ARN: arn:aws:kms:REGION:ACCOUNT-ID:alias/YOUR-PROJECT-NAME_PROD_APP_SECRETS
    kms: 'arn:aws:kms:YOUR-AWS-REGION:YOUR-AWS-ACCOUNT-ID:alias/YOUR-PROJECT-NAME_PROD_APP_SECRETS'
